// projects/game-app/src/app/hud/hud.component.ts
import { Component, ViewChild, ElementRef, OnInit, Input, ChangeDetectionStrategy, OnDestroy } from "@angular/core";
import { EventManager } from '@libutil/eventmanager';
import { GameAppUIEvents } from '../../services/gameappuieventmanager';

@Component({
  selector: 'game-hud',
  templateUrl: './hud.component.html',
  styleUrls: ['./hud.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HudComponent implements OnInit, OnDestroy {
  @ViewChild('redHealthBar') redHealthBar: ElementRef<HTMLDivElement>|undefined;
  @ViewChild('greenHealthBar') greenHealthBar: ElementRef<HTMLDivElement>|undefined;
  @ViewChild('healthBarText') healthBarText: ElementRef<HTMLDivElement>|undefined;

  @Input('uiEventManager') uiEventManager: EventManager<GameAppUIEvents>|undefined;

  private playerHealthListener_: ((playerHealthEvent: any)=>void)|undefined;

  ngOnInit() {
    if (!this.redHealthBar || !this.greenHealthBar || !this.healthBarText) {
      throw new Error('Could not get all UI elements for the HUD');
    }

    if (!this.uiEventManager) {
      throw new Error('Failed to inject UI event manager, cannot construct UI');
    }

    this.playerHealthListener_ =
      this.uiEventManager.addListener('playerhealth', (playerHealthEvent) => {
        this.healthBarText!.nativeElement.innerText =
            `${Math.round(playerHealthEvent.CurrentHealth)} / ${playerHealthEvent.MaxHealth}`;
      // TODO (sessamekesh): Animate the bar smaller
      const healthAmt = playerHealthEvent.CurrentHealth / playerHealthEvent.MaxHealth;
      const width = Math.round(healthAmt * 500);
      this.redHealthBar!.nativeElement.style.width = `${width}px`;
      this.greenHealthBar!.nativeElement.style.width = `${width}px`;
    });
  }

  ngOnDestroy() {
    if (this.playerHealthListener_ && this.uiEventManager) {
      this.uiEventManager.removeListener('playerhealth', this.playerHealthListener_);
    }
  }
}

<div class="hud-outer">
  <div class="row">
    Bike Health:
    <div class="health-bar">
      <div #redHealthBar class="health-bar-red"></div>
      <div #greenHealthBar class="health-bar-green"></div>
      <div #healthBarText class="health-bar-text"></div>
    </div>
  </div>
</div>

// projects/game-app-react/src/hud/hud.tsx
import * as React from 'react';
import './hud.scss';

import { GameAppUIEvents } from '../services/gameappuieventmanager';
import { CachingEventManager } from '@libutil/cachingeventmanager';

interface Props {
  uiEventManager: CachingEventManager<GameAppUIEvents>,
}

interface State {}

export class HUD extends React.Component<Props, State> {
  readonly state: State = {};

  private redHealthBar: HTMLDivElement|null = null;
  private greenHealthBar: HTMLDivElement|null = null;
  private healthBarText: HTMLDivElement|null = null;

  private onDestroy: (()=>void)[] = [];

  componentDidMount() {
    if (!this.redHealthBar || !this.greenHealthBar || !this.healthBarText) {
      throw new Error('Could not get all UI elements for the HUD');
    }

    const playerHealthListener = this.props.uiEventManager.addListener('playerhealth', (health) => {
      if (!this.healthBarText || !this.redHealthBar || !this.greenHealthBar) return;
      this.healthBarText.innerText = `${Math.round(health.CurrentHealth)} / ${health.MaxHealth}`;

      const healthAmt = health.CurrentHealth / health.MaxHealth;
      const width = Math.round(healthAmt * 500);

      this.redHealthBar.style.width = `${width}px`;
      this.greenHealthBar.style.width = `${width}px`;
    });
    this.onDestroy.push(
      ()=>this.props.uiEventManager.removeListener('playerhealth', playerHealthListener));
  }

  componentWillUnmount() {
    this.onDestroy.forEach(e=>e());
  }

  render() {
    return <div className="hud-outer">
      <div className="row">
        Bike Health:
        <div className="health-bar">
          <div className="health-bar-red" ref={(r)=>this.redHealthBar=r} />
          <div className="health-bar-green" ref={(r)=>this.greenHealthBar=r} />
          <div className="health-bar-text" ref={(r)=>this.healthBarText=r} />
        </div>
      </div>
    </div>
  }
}
